version: '3'

#FORM node:20-slim

services:


  db:
    image: mysql:5.7 
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

