version: '3'

services:

  app:
    build: 
      context: node
    container_name: app
    networks:
      - node-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node ./node/index.js
    volumes:
      - .:/usr/src/app
      - exclude:/usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7 
    command: --innodb-use-native-aio=0
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - node-network

  nginx:
    restart: always
    build: 
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app    

networks:
  node-network:
    driver: bridge

volumes:
  exclude: